// Represents a row of data returned from BigQuery.

export interface BigQueryRow {
	[key: string]: any
}

/**
 * Asynchronously queries data from BigQuery.
 *
 * @param query The SQL query to execute.
 * @returns A promise that resolves to an array of BigQueryRow objects.
 */
export async function queryBigQuery(
	query: string,
	clientName: string,
): Promise<BigQueryRow[]> {
	// TODO: Implement this by calling the BigQuery API.
	console.log(`Executing query for client ${clientName}: ${query}`)

	// Mock data for testing - simulates a more diverse financial dataset
	const mockData: BigQueryRow[] = [
		{
			id: "1",
			transaction_date: "2024-01-01",
			amount: 100.0,
			description: "Office Supplies",
			ai_vendor: "Staples",
			ai_category: "Supplies",
			vendor_name: "Staples",
			category: "Office Supplies",
			is_enriched: true,
			source_file: "file1.csv",
			file_id: "abc1",
			notes: "Purchase of pens and paper",
			general_category: "Administration",
			cluster_id: 1,
		},
		{
			id: "2",
			transaction_date: "2024-01-05",
			amount: 500.0,
			description: "Consulting Services",
			ai_vendor: "Accenture",
			ai_category: "Professional Services",
			vendor_name: "Accenture",
			category: "Consulting",
			is_enriched: true,
			source_file: "file2.csv",
			file_id: "def2",
			notes: "Strategy consulting",
			general_category: "Programs",
			cluster_id: 2,
		},
		{
			id: "3",
			transaction_date: "2024-01-10",
			amount: 250.0,
			description: "Travel Expenses",
			ai_vendor: "United Airlines",
			ai_category: "Travel",
			vendor_name: "United Airlines",
			category: "Airfare",
			is_enriched: true,
			source_file: "file3.csv",
			file_id: "ghi3",
			notes: "Conference travel",
			general_category: "Administration",
			cluster_id: 3,
		},
		{
			id: "4",
			transaction_date: "2024-01-15",
			amount: 1200.0,
			description: "Software Subscription",
			ai_vendor: "Adobe",
			ai_category: "Software",
			vendor_name: "Adobe",
			category: "Software Subscriptions",
			is_enriched: true,
			source_file: "file4.csv",
			file_id: "jkl4",
			notes: "Annual subscription for creative suite",
			general_category: "Technology",
			cluster_id: 4,
		},
		{
			id: "5",
			transaction_date: "2024-01-20",
			amount: 75.0,
			description: "Internet Service",
			ai_vendor: "Comcast",
			ai_category: "Utilities",
			vendor_name: "Comcast",
			category: "Internet",
			is_enriched: true,
			source_file: "file5.csv",
			file_id: "mno5",
			notes: "Monthly internet bill",
			general_category: "Administration",
			cluster_id: 5,
		},
		{
			id: "6",
			transaction_date: "2024-01-25",
			amount: 300.0,
			description: "Marketing Campaign",
			ai_vendor: "Facebook Ads",
			ai_category: "Advertising",
			vendor_name: "Facebook",
			category: "Online Advertising",
			is_enriched: true,
			source_file: "file6.csv",
			file_id: "pqr6",
			notes: "Social media advertising campaign",
			general_category: "Marketing",
			cluster_id: 6,
		},
		{
			id: "7",
			transaction_date: "2024-01-30",
			amount: 800.0,
			description: "Rent Payment",
			ai_vendor: "Landlord Inc.",
			ai_category: "Facilities",
			vendor_name: "Landlord Inc.",
			category: "Rent",
			is_enriched: true,
			source_file: "file7.csv",
			file_id: "stu7",
			notes: "Monthly office rent",
			general_category: "Administration",
			cluster_id: 7,
		},
		{
			id: "8",
			transaction_date: "2024-02-05",
			amount: 60.0,
			description: "Coffee Supplies",
			ai_vendor: "Starbucks",
			ai_category: "Supplies",
			vendor_name: "Starbucks",
			category: "Office Supplies",
			is_enriched: false,
			source_file: "file8.csv",
			file_id: "vwx8",
			notes: "Coffee and tea for the office",
			general_category: "Administration",
			cluster_id: 1,
		},
		{
			id: "9",
			transaction_date: "2024-02-10",
			amount: 400.0,
			description: "Staff Training",
			ai_vendor: "Udemy",
			ai_category: "Professional Development",
			vendor_name: "Udemy",
			category: "Training",
			is_enriched: true,
			source_file: "file9.csv",
			file_id: "yz19",
			notes: "Online courses for staff",
			general_category: "Programs",
			cluster_id: 2,
		},
		{
			id: "10",
			transaction_date: "2024-02-15",
			amount: 150.0,
			description: "Printing Services",
			ai_vendor: "FedEx Office",
			ai_category: "Supplies",
			vendor_name: "FedEx Office",
			category: "Printing",
			is_enriched: true,
			source_file: "file10.csv",
			file_id: "2340",
			notes: "Printing brochures for event",
			general_category: "Marketing",
			cluster_id: 6,
		},
	]

	return mockData
}
